name: release-ci

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: CWD 
      run:  echo $(GITHUB_WORKSPACE) && ls -la
              

    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2.2.0

    - name: Test with Zig
      run: zig test src/main.zig

    - name: Build with Zig
      run: zig build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snak-bin
        path: ./zig-out/bin/snak
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: snak-bin

    - name: Create Release
      id: create_release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.create_release.outputs.upload_url }}
